title: ThinkPrivacy
description: With corporate and government sponsored surveillance programs exploiting your data for profit or motive, isn't it time you started to Think Privacy?
url: "https://thinkprivacy.io"
markdown: kramdown
collections:
  authors:
  output: true
plugins:
- jekyll-sitemap
- jekyll-feed  
sitemap:
file: "/sitemap.xml"
exclude: [vendor, LICENSE, build.sh, README.md, Gemfile, Gemfile.lock]
include: [.well-known, keybase.txt]